### ISSUE TITLE
[FHIR] add readinessProbe to deployment.yaml

### ISSUE THREAD

**Issue by michaelwschroeder** [Alvearie/alvearie-helm#13]
We need to add a readinessProbe which calls $healthcheck using exec vs. http since we need to grab the user password from an environment variable.

**Comment by lmsurpre** [comment]
If we needed just the env var's value we could use the kubernetes support for env var interpolation via `$( )`.
Unfortunately, we're trying to use it with an HTTP readiness probe and that doesn't support basic auth except for setting the Authentication header yourself.  So we'd actually need to be able to base64 encode the `username:password` and there is no way to do that from an HTTP readiness probe without writing that password (albeit encoded) right into the deployment yaml.

Instead, the password should be kept in a secret.
