### ISSUE TITLE
Include postgres as an optional sub-chart to make it easier to install the server

### ISSUE THREAD

**Issue by lmsurpre** [Alvearie/alvearie-helm#27]
probably using the bitnami postgresql chart

see https://github.com/chgl/charts/blob/master/charts/hapi-fhir-jpaserver/Chart.yaml#L10 for an example

**Comment by chgl** [comment]
It's slightly more challenging than I had anticipated: currently, the `create-schemas` job is run before any other resources are created (via it's pre-install annotation). So it assumes that the DB exists before `helm install` is run. If the database is part of the chart itself, then the job will wait indefinitely for the database to be up. A two ideas for an alternative solution:

1. run the `create-schema` and `update-schema` as initContainers that are part of the server deployment. The initContainers are run in-order, so this should work. What I am unsure about is (a) whether these migration jobs still work well if multiple are run at the same time, e.g. the chart is installed with two replicas of the server pod and therefore two instances of the init containers running simultaneously, and (b) do the jobs exit gracefully if the database is already initialized, e.g. if the pod gets rescheduled and the migration jobs run for an already-initialized database again.
2. keep the migration jobs as they are (maybe merged into a single job with a slightly more elaborate shell script to run `create` followed by `update`), but add an initContainer to the deployment which waits for the job to be completed. This could be a call to the Kubernetes API polling the job status or alternatively an SQL query which succeeds if the database is fully initialized.

**Comment by lmsurpre** [comment]
The schema tool is designed to be idempotent (safe to run multiple times), but I'm a little nervous about running it on each of the different pods during startup, which is why I thought it was a nice use case for helm hooks.
Running the create/update schema on a lot of pods at once seems like it could be asking for trouble.  Is there a common pattern to serialize those in kubernetes/helm or would we need to build the locking right into the db (within our schema tool)?

**Comment by chgl** [comment]
I agree helm hooks are great for this. They to some extent even work with entirely declarative deployment approaches like gitops (https://argoproj.github.io/argo-cd/user-guide/helm/#helm-hooks). ordering is always a challenge, though. Let's keep the jobs then. Is there a way to determine if the migration jobs have completed maybe some sort of version column within the database? - it could be used to determine when to start the server.

Another way to ensure ordering is using an operator (e.g. the Strimzi Kafka Operator starts the zookeeper cluster before creating the Kafka Cluster resources), but I think this is overkill here.

**Comment by lmsurpre** [comment]
> Is there a way to determine if the migration jobs have completed maybe some sort of version column within the database?

There is a "fhir_admin" schema where we track the version of all the various table schemas, but I don't think we have a simple / single place to get the overall level of the db (one which isn't written until a complete install / migration has occurred).  I opened #2751 so that we can make the init container approach a bit safer.

**Comment by chgl** [comment]
I've now updated my implementation in https://github.com/Alvearie/alvearie-helm/pull/28 to run both the schema tasks and the  server simultaneously. ... it seems to start alright. The create-schema job runs quickly enough to be done before the actual server tries to connect to the DB (and expect the schema to exist) for the first time. Let me know if you think this approach is OK and you or someone in your team would like to review it.
