### ISSUE TITLE
Support for adding a java agent for application performance monitoring

### ISSUE THREAD

**Issue by lmsurpre** [Alvearie/alvearie-helm#46]
In a few cloud deploys, we're using newrelic for application performance monitoring.  It would be nice if the chart let us add that.  I think it consists of just a few things:
1. add the newrelic jar(s) and supporting files (e.g. newrelic.yml) to the image.  one way I've seen this done is to declare the dependencies via maven, unpack them in a known location (e.g. `/opt/ol/wlp/newrelic/newrelic.jar`)
    * as an alternative to putting config into a newrelic.yml, its possible to set the key fields like `licence_key` and `app_name` via [Environment Variables](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file/#Environment_Variables)
2. add the javaagent argument to jvm.options (e.g. `-javaagent:/opt/ol/wlp/newrelic/newrelic.jar`)

It would be nice if this were done in such a way to support *any* application performance monitoring solution.

**Comment by chgl** [comment]
Maybe https://github.com/open-telemetry/opentelemetry-java-instrumentation is helpful as well - but I have to admit to not being sure how well it works with NewRelic (or how it works at all).

**Comment by lmsurpre** [comment]
Using the new `extraJvmOptions` and `extraEnv` helm values, its now possible to pass a `-javaagent` string as well as custom environment variables.

For newrelic, this might look like the following:
1. a custom docker image that includes the newrelic jar and its config template:
```
FROM ibmcom/ibm-fhir-server

COPY --chown=1001:0 newrelic/newrelic.jar /opt/ol/wlp/newrelic/
COPY --chown=1001:0 newrelic/newrelic.yml /opt/ol/wlp/newrelic/
```

2. a values override that sets the javaagent property, as well as some newrelic-specific env vars:
```
extraJvmOptions: |
  -javaagent:/opt/ol/wlp/newrelic/newrelic.jar

  - name: NEW_RELIC_APP_NAME
    value: "accountName:clusterName:{{ $.Release.Namespace }}:{{ template "fhir.fullname" $ }}"
  - name: NEW_RELIC_HIGH_SECURITY
    value: "true"
  - name: NEW_RELIC_LOG_LEVEL
    value: "info"
  - name: NEW_RELIC_LICENSE_KEY
    value: ****
```

The open-telemtry stuff looks solid.  I'm hoping the same generic hooks would work for that one and I hope I'll get to try it out at some point.  If you find we need something more, feel free to open an issue for it.
