### ISSUE TITLE
[FHIR] Support for custom trust stores

### ISSUE THREAD

**Issue by lmsurpre** [Alvearie/alvearie-helm#6]
The IBM FHIR Server ships with a default trust store which is set up to trust the fhir-client's client cert.
We also have an environment variable named SEC_TLS_TRUSTDEFAULTCERTS which defaults to true.
When true, the server will also trust anything that is trusted by the underlying java runtime.

However, for in-cluster dbs or certain managed dbs like the IBM Cloud Databases for PostgreSQL, we need the ability to configure the ibm-fhir-server with a custom trust store entry so that it can connect to the db over TLS.

**Comment by michaelwschroeder** [comment]
We will enable the user to pass in their own keystore and truststore files via Secrets. The following values will be added to the `values.yaml` file to specify the Secret names:
- `keyStoreSecret`
- `trustStoreSecret`

For the truststore Secret, it will be expected to contain the content of the truststore file, the filename, and the password. The expected Secret keys are as follows:

| Key | Value |
|-----|-------|
|`fhirTrustStore`|The contents of the truststore file|
|`fhirTrustStoreFilename`|The name of the truststore file|
|`fhirTrustStorePassword`|The truststore password|

If a truststore secret is not specified, the default truststore will be used.

**Comment by michaelwschroeder** [comment]
Small design update:

We will enable the user to pass in their own keystore and truststore files via Secrets. The following values will be added to the `values.yaml` file to specify the Secret names and file format:
- `keyStoreSecret`
- `keyStoreFormat`
- `trustStoreSecret`
- `trustStoreFormat`

For the truststore Secret, it will be expected to contain the content of the truststore file and the password. The expected Secret keys are as follows:

| Key | Value |
|-----|-------|
|`fhirTrustStore`|The contents of the truststore file|
|`fhirTrustStorePassword`|The truststore password|

If a truststore secret is not specified, the default truststore will be used.
